[project]
name = "quantumaudio"
version = "0.1.0"
dependencies = ["qiskit==0.46.0","qiskit_aer==0.13.3","numpy==1.26.4","bitstring==4.2.3","matplotlib==3.8.4","pylatexenc==2.10","tqdm"]

[project.optional-dependencies]
audio_io = ["soundfile==0.12.1","librosa==0.10.2.post1"]
notebook_examples = ["ipython==8.12.3","ipykernel==6.29.5","ipywidgets==8.1.2"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = ["D"]